### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by JulioPDX**
Minor correction on fail message.

### CODE REVIEW

**Comment by ddutt** [comment]
@JulioPDX Could you please signoff the commit? You do that with a git commit -s (or git commit --sign-off).

**Comment by JulioPDX** [comment]
Will do first thing in the morning. Thank you!

**Comment by JulioPDX** [comment]
@ddutt I think this is resolved now. Please let me know if you need anything else.

**Comment by zxiiro** [comment]
@JulioPDX your commits need to have a "Signed-off-by:" line to pass the DCO check. I'd recommend rebasing your commits and squashing them into a single commit with the signed-off-by line in the footer.

**Comment by JulioPDX** [comment]
I can tackle that this week. I'll remove this request and start fresh.
Thank you!

**Comment by JulioPDX** [comment]
Closing and going to publish new with sign off

**Pull request closed without merging**
