### PR TITLE
fix minor typos in README.md

### PR DESCRIPTION
**Pull request by vivekvashist**
# Set `develop` as target branch of this PR (delete this line before issuing the PR)

## Test inclusion requirements

In case the PR contains an enhancement or a new platform/service support, some tests have to be added for the new functionality:

- any fix or enhancement SHOULD include relevant new tests or test updates, if any tests need updating.
- a new platform support MUST include the relevant input files similar to what we have in tests/integration/sqcmds/-input directories, along with the relevant tests in the tests/integration/sqcmds/-samples dir. That list MUST include the all.yml file fully filled out.
- any new service (or table) addition MUST include comments about what network OS are supported (along with version) with this command along with test samples for those platforms and input files in the *-input dir

For additional information about tests, follow this [link](https://suzieq.readthedocs.io/en/latest/developer/testing/)

## Related Issue

Fixes #

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation update

## New Behavior

...

## Contrast to Current Behavior

...

## Discussion: Benefits and Drawbacks

...

## Changes to the Documentation

...

## Proposed Release Note Entry

...

## Comments

Include additional comments about the this pull request

## Double Check

- [x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netenglabs/suzieq/blob/master/CONTRIBUTING.md).
- [x] I have explained my PR according to the information in the comments or in a linked issue.
- [ ] My PR source branch is created from the `develop` branch.
- [ ] My PR targets the `develop` branch.
- [x] All my commits have `--signoff` applied

### CODE REVIEW

**Review by ddutt — APPROVED** [review]

**Comment by ddutt** [comment]
Thanks for the contribution, @vivekvashist

**Review by LucaNicosia — APPROVED** [review]

**Comment by ddutt** [comment]
@vivekvashist please add a sign-off to your commit, or we cannot accept it.

**Review by ddutt — CHANGES_REQUESTED** [review]
Please add a sign-off to your commit

**Comment by mjbear** [comment]
> @vivekvashist please add a sign-off to your commit, or we cannot accept it.

@vivekvashist 
:bulb: For your existing commits, you'll want to run `git commit --amend --signoff`
(I don't think Dinesh will need you to sign your merge commit, but if you wanted to do that add in `HEAD~2` to the above command. Probably best to just do so to be safe.)

:1st_place_medal: While performing commits the sign off text can be added like so `git commit --signoff` (enter your commit message and save). If you use a GUI for the commits there might be settings to enable --signoff.

I hope this helps.
(Beware the longer this PR goes unmerged the more chances of a merge conflict that will need resolved.)

**Comment by vivekvashist** [comment]
I'll resubmit this shortly.

**Comment by mjbear** [comment]
> I'll resubmit this shortly.

Why close this one and resubmit?

You were almost done. :grinning: There was one step needed (`--signoff`) and the rest was viable since Dinesh did not point out any other issues.

:bulb: You can always re-open this PR, fix up the commit signing, and have it ready for the SuzieQ team.

**Pull request closed without merging**
